# Path to project
project:
    base-dir: classpath:.

# Templates reloading during development
# Static resources reloading during development
spring:
    thymeleaf:
        prefix: ${project.base-dir}/templates/
        cache: false
    resources:
        static-locations: ${project.base-dir}/static/
        cache-period: 0